# README: https://github.com/jbensmann/mouseless
#
# The layout is inspired from my Moonlander 34 keys layout.
# https://configure.zsa.io/moonlander/layouts/qYJo5/latest/0

# The keyboard devices it reads from, if no devices are specified, it reads
# from all.
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# The default speed for mouse movement and scrolling.
baseMouseSpeed: 800.0
baseScrollSpeed: 10.0
# The time it takes to accelerate to baseMouseSpeed (in ms), 0 to reach top
# speed immediately.
mouseAccelerationTime: 200.0
# The shape of the acceleration curve, 1.0 is linear, higher values have more
# time at low speeds.
mouseAccelerationCurve: 2.0
# Speed of the mouse when it starts moving.
startMouseSpeed: 0.0
# Same for deceleration.
mouseDecelerationTime: 200.0
mouseDecelerationCurve: 3.0

# The best way for hodling keys is
# `a_key: tap-hold-next-release a_key ; something ; 0`.
# https://github.com/jbensmann/mouseless/issues/40
.definitions:
  # Layer common bindings.
  - &common
    z: tap-hold-next-release z ; leftctrl ; 0
    x: tap-hold-next-release x ; leftshift ; 0
    # TODO: Comment out as the response for c key is not good.
    # Can't use leftalt as it is assigned.
    # c: tap-hold-next-release c ; rightalt ; 0
    comma: tap-hold-next-release comma ; rightalt ; 0
    dot: tap-hold-next-release dot ; rightshift ; 0
    slash: tap-hold-next-release slash ; rightctrl ; 0

  # Always return to the base layer on any layer.
  - &return-to-base
    # leftmeta: layer base
    leftalt: layer base
    # rightalt: layer base

  # Toggle the layer control.
  - &toggle-layer-control
    # leftctrl: tap-hold-next-release leftctrl ; toggle-layer mouse ; 0
    leftmeta: tap-hold-next-release leftmeta ; toggle-layer control ; 0
    # leftmeta: tap-hold-next-release leftmeta ; toggle-layer mouse ; 0
    # leftmeta: tap-hold-next-release leftmeta ; toggle-layer control ; 0
    # leftalt: tap-hold-next-release leftalt ; toggle-layer control ; 0
    # space: tap-hold-next-release space ; toggle-layer control ; 0

layers:
- name: base
  bindings:
    <<: *common
    <<: *toggle-layer-control

    d: tap-hold-next-release d ; toggle-layer symbol-shift ; 0
    f: tap-hold-next-release f ; toggle-layer symbol ; 0

    j: tap-hold-next-release j ; toggle-layer symbol ; 0
    k: tap-hold-next-release k ; toggle-layer symbol-shift ; 0

- name: control
  passThrough: true
  bindings:
    a: esc

    d: layer nav
    f: layer mouse

    i: tab

    h: backspace
    j: enter
    # semicolon: layer symbol

- name: mouse
  # When true, keys that are not mapped keep their original meaning.
  passThrough: true
  bindings:
    <<: *common
    <<: *return-to-base

    space: button left

    # Close Tab
    q: rightctrl+w
    # Open Tab
    w: rightctrl+t
    # Prev Tab
    e: rightctrl+rightshift+tab
    # Next Tab
    r: rightctrl+tab

    a: speed 2.0
    s: speed 0.5
    d: speed 0.3
    f: speed 0.1

    v: button right

    u: scroll down
    i: scroll up
    # Go Back
    o: rightalt+left
    # Go Foward
    p: rightalt+right

    h: move -1  0
    j: move  0  1
    k: move  0 -1
    l: move  1  0
    semicolon: layer nav

    n: button right
    m: button right

- name: nav
  passThrough: true
  bindings:
    <<: *common
    <<: *return-to-base
    <<: *toggle-layer-control

    space: rightshift

    q: reload-config

    a: layer mouse
    # Can't use leftalt as it is assigned.
    s: rightalt
    d: rightctrl
    f: rightshift

    u: pagedown
    i: pageup
    o: home
    p: end

    h: left
    j: down
    k: up
    l: right
    semicolon: layer mouse

    n: backspace
    m: enter

- name: symbol
  passThrough: true
  bindings:
    <<: *common
    <<: *return-to-base
    <<: *toggle-layer-control
    leftshift: tap-hold-next-release leftshift ; toggle-layer symbol-shift ; 0
    rightshift: tap-hold-next-release rightshift ; toggle-layer symbol-shift ; 0

    q: k1
    w: k2
    e: k3
    r: k4
    t: k5

    a: esc
    s: leftbrace
    d: rightbrace
    f: tab
    g: sysrq

    # backquote
    # z: grave
    z: tap-hold-next-release grave ; leftctrl ; 0

    y: k6
    u: k7
    i: k8
    o: k9
    p: k0

    h: backspace
    j: enter
    k: minus
    l: equal
    # single-quote
    semicolon: apostrophe

    # slash: backslash
    slash: tap-hold-next-release backslash ; rightctrl ; 0

- name: symbol-shift
  passThrough: true
  bindings:
    <<: *return-to-base

    q: rightshift+k1
    w: rightshift+k2
    e: rightshift+k3
    r: rightshift+k4
    t: rightshift+k5

    s: rightshift+leftbrace
    d: rightshift+rightbrace
    f: rightshift+tab

    # backquote
    z: rightshift+grave

    y: rightshift+k6
    u: rightshift+k7
    i: rightshift+k8
    o: rightshift+k9
    p: rightshift+k0

    h: delete
    j: insert
    k: rightshift+minus
    l: rightshift+equal
    # double-quote
    semicolon: rightshift+apostrophe

    slash: rightshift+backslash
