# README: https://github.com/jbensmann/mouseless
#
# The layout is inspired from my Moonlander 34 keys layout.
# https://configure.zsa.io/moonlander/layouts/qYJo5/latest/0

# The keyboard devices it reads from, if no devices are specified, it reads
# from all.
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# The default speed for mouse movement and scrolling.
baseMouseSpeed: 800.0
baseScrollSpeed: 10.0
# The time it takes to accelerate to baseMouseSpeed (in ms), 0 to reach top
# speed immediately.
mouseAccelerationTime: 200.0
# The shape of the acceleration curve, 1.0 is linear, higher values have more
# time at low speeds.
mouseAccelerationCurve: 2.0
# Speed of the mouse when it starts moving.
startMouseSpeed: 0.0
# Same for deceleration.
mouseDecelerationTime: 200.0
mouseDecelerationCurve: 3.0

.definitions:
  # Layer common bindings.
  - &common
    z: tap-hold-next-release z ; leftctrl ; 0
    slash: tap-hold-next-release slash ; rightctrl ; 0
  # Always return to the base layer on any layer.
  - &return-to-base
    leftmeta: layer base
    leftalt: layer base

layers:
- name: base
  bindings:
    # The best way for hodling keys is
    # `a_key: tap-hold-next-release a_key ; something ; 0`.
    # https://github.com/jbensmann/mouseless/issues/40

    # a: tap-hold-next-release a ; toggle-layer control ; 0
    # leftmeta: tap-hold-next-release leftmeta ; toggle-layer control ; 0
    capslock: tap-hold-next-release capslock ; toggle-layer control ; 0
    # space: tap-hold-next-release space ; toggle-layer control ; 0

    # d: tap-hold-next-release d ; leftctrl ; 0
    # f: tap-hold-next-release f ; leftshift ; 0

    # j: tap-hold-next-release j ; rightshift ; 0
    # k: tap-hold-next-release k ; rightctrl ; 0

    <<: *common

- name: control
  passThrough: true
  bindings:
    u: tab
    i: esc

    h: backspace
    j: enter
    k: layer mouse
    l: layer nav
    semicolon: layer symbol

- name: mouse
  # When true, keys that are not mapped keep their original meaning.
  passThrough: true
  bindings:
    <<: *return-to-base
    space: button left
    rightalt: button right

    # Close Tab
    q: rightctrl+w
    # Open Tab
    w: rightctrl+t
    # Prev Tab
    e: rightctrl+rightshift+tab
    # Next Tab
    r: rightctrl+tab

    a: speed 2.0
    s: speed 0.5
    d: speed 0.3
    f: speed 0.1

    u: scroll down
    i: scroll up
    # Go Back
    o: rightalt+left
    # Go Foward
    p: rightalt+right

    h: move -1  0
    j: move  0  1
    k: move  0 -1
    l: move  1  0
    semicolon: layer nav

- name: nav
  passThrough: true
  bindings:
    <<: *return-to-base
    rightalt: backspace

    q: reload-config

    a: layer mouse
    # Can't use leftalt as it is assigned.
    s: rightalt
    d: rightctrl
    f: rightshift

    u: pagedown
    i: pageup
    o: home
    p: end

    h: left
    j: down
    k: up
    l: right
    semicolon: layer mouse

    n: backspace
    m: enter

- name: symbol
  passThrough: true
  bindings:
    <<: *return-to-base
    leftshift: tap-hold-next-release leftshift ; toggle-layer symbol-shift ; 0
    rightshift: tap-hold-next-release rightshift ; toggle-layer symbol-shift ; 0

    q: k1
    w: k2
    e: k3
    r: k4
    t: k5

    a: esc
    s: leftbrace
    d: rightbrace
    f: tab
    g: sysrq

    # backquote
    z: grave
    x: delete
    c: insert

    y: k6
    u: k7
    i: k8
    o: k9
    p: k0

    h: backspace
    j: enter
    k: minus
    l: equal
    # single-quote
    semicolon: apostrophe

    slash: backslash

    <<: *common

- name: symbol-shift
  passThrough: true
  bindings:
    <<: *return-to-base

    q: rightshift+k1
    w: rightshift+k2
    e: rightshift+k3
    r: rightshift+k4
    t: rightshift+k5

    s: rightshift+leftbrace
    d: rightshift+rightbrace
    f: rightshift+tab

    # backquote
    z: rightshift+grave

    y: rightshift+k6
    u: rightshift+k7
    i: rightshift+k8
    o: rightshift+k9
    p: rightshift+k0

    k: rightshift+minus
    l: rightshift+equal
    semicolon: rightshift+apostrophe

    slash: rightshift+backslash
